### PR TITLE
Fix to ssh context to handle passwords containing spaces

### PR DESCRIPTION
**Pull request by jcohen02**
Proposed fix to #509. This takes spaces into account but not sure whether there are other characters that may also cause similar issues. Perhaps someone can review and see if this looks reasonable.

### CODE REVIEW

**Comment by marksantcroos** [comment]
Would the following work also?

```
"ssh-keygen -y -f %s -P '%s' > /dev/null"
```

If so, then it will work for most other characters too.

**Comment by andre-merzky** [comment]
I would agree with Mark here: quoting seems easier and more generic?

**Comment by andre-merzky** [comment]
Hi Jeremy -- any comment?

**Comment by jcohen02** [comment]
Hi, yes, I'd agree Mark's suggestion seems like a better option. I'll make the fix and update the branch.

**Comment by andre-merzky** [comment]
Thanks!

**Comment by jcohen02** [comment]
I've updated the fix as per Mark's suggestion and tested it. All seems ok.

**Comment by andre-merzky** [comment]
Many thanks, Jeremy! :)

**Pull request merged**
