### PR TITLE
re-enable fallback methods for slurm job containers, jd.name support

### PR DESCRIPTION
**Pull request by andre-merzky**
This gets the `split_module` branch (and thus `experiment/aimes`) running on stampede.

### CODE REVIEW

**Comment by marksantcroos** [comment]
With this branch I get:
```
2016-10-03 09:02:17,777: pmgr.launching.0.child: pmgr.launching.0                : pmgr.launching.0.child.idler._pilot_watcher_cb: ERROR   : TERM : pmgr.launching.0.child idler failed pmgr.launching.0.child.idler._pilot_watcher_cb
Traceback (most recent call last):
  File "/Users/mark/aimes/ve/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 1048, in _idler
    callback()
  File "/Users/mark/aimes/ve/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 180, in _pilot_watcher_cb
    states = tc.get_states()
  File "/Users/mark/aimes/ve/lib/python2.7/site-packages/saga/task.py", line 641, in get_states
    raise thread.get_exception ()
NotImplemented: Service.run is not implemented for saga.SLURMJobService (container_get_states) (/Users/mark/aimes/ve/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py +80 (wrap_function)  :  inspect.getmembers (cpi_sync_function)[15][1])))
```

Maybe related, shouldn't this have been branched of/merged towards experiments/aimes instead of devel?

**Comment by andre-merzky** [comment]
the PR is toward devel as its is not aimes specific or anything -- it adds generic container fallback methods to slurm.

What exactly are you running here on the RP end?  I still can't reproduce it :/

**Comment by andre-merzky** [comment]
Thanks Mark, I see that now - I missed that this was on the state pull, not the submission.  This should be fixed now.

**Comment by marksantcroos** [comment]
Thanks. It's working on Comet, but fails on Stampede because of the issue reported in `[saga-devel:1309]`.

**Comment by andre-merzky** [comment]
Hmm, it works for me on Stampede actually.  But I am not sure what the saga issue 1309 is, I don't see that, so I might be missing something?

**Comment by marksantcroos** [comment]
> But I am not sure what the saga issue 1309 is, I don't see that, so I might be missing something?

Message to the saga-devel mailing list about `/tmp/t`.

> Hmm, it works for me on Stampede actually.

That's because `/tmp/t` on the headnode is owned by you probably.

**Pull request merged**
