### PR TITLE
Add session property to base class. Fix #480.

### LINKED ISSUE #480: use _set_session() / get_session() in all adaptors
see #477/#479

### PR DESCRIPTION
**Pull request by mehdisadeghi**
Hi Andre,

as discussed #480, here is the PR. Let's fix it all :)

P.S. I still have problems while working with upstream. Git creates merge commits when I want to sync my branch. If it makes any problem, please let me know how and I will try to correct it.

### CODE REVIEW

**Comment by marksantcroos** [comment]
> P.S. I still have problems while working with upstream. Git creates merge commits when I want to sync my branch. If it makes any problem, please let me know how and I will try to correct it.

You can use `git rebase` if you really want, but we dont mind the extra commits too much.
Rebase requires more care.

**Comment by mehdisadeghi** [comment]
>> You can use git rebase if you really want, but we dont mind the extra commits too much.
>> Rebase requires more care.

Thanks @marksantcroos, I just figured it out. From now on, I will create a fresh branch and cherry pick the commits that I want to create a pull request for. It works like charm!

**Comment by andre-merzky** [comment]
Thanks for the PR, Mehdi, very much appreciated!

A.

**Comment by mehdisadeghi** [comment]
You're welcome! BTW, when do you plan to have a release and merge devel into master?

**Comment by andre-merzky** [comment]
We have no specific release plan for SAGA at the moment -- so please speak up if you would benefit from a release, then we can start getting testing and release procedure started!

**Comment by mehdisadeghi** [comment]
@andre-merzky Currently I have to ask our users to use `devel` branch, otherwise our central setup will not work. Therefore, we definitely benefit from a new release which incorporates the recent changes to devel branch! Shall I make an issue for this to proceed?

**Pull request merged**
