### PR TITLE
Feature/slurm reservation

### PR DESCRIPTION
**Pull request by andre-merzky**
IIRC, this was ready for merge back in Julich?

### CODE REVIEW

**Comment by marksantcroos** [comment]
It's never tested/used. So if you want to merge it, then please give it a review.

**Comment by andre-merzky** [comment]
Ah, ok -- I thought that was used in the tutorial, but IIRC, that reservation was changed into a specific queue at the end or something?  Anyway,  I don't have a slurm reservation anyway, and don't want to spend time on setting slurm up for testing right now, so I guess we'll leave this open 'til later then...

Thanks!

**Comment by marksantcroos** [comment]
Given that I wrote it, I shouldnt be reviewing it :)
Anyway, lets wait on @iparask, now that we have a real use-case after all.

**Comment by andre-merzky** [comment]
RIght - I did review it and it looks good, but could not test... :/  So yeah, lets wait for confirmation from Giannis...

**Comment by andre-merzky** [comment]
Giannis, please open a ticket if that breaks...

**Pull request merged**
