### PR TITLE
Document missing path normalization

### PR DESCRIPTION
**Pull request by mturilli**

### CODE REVIEW

**Comment by mturilli** [comment]
@andre-merzky can we fix the tests so that they pass in Travis?

**Comment by andre-merzky** [comment]
Thanks for the PR, Matteo!  Alas, it will not really resolve the issue, since the double slashes are often ingested from other pieces of code, and that API path (where the URL elements are set individually) does then not apply.

I tried to provide a code fix in radical-cybertools/radical.utils/pull/159 - can you have a look if that looks ok for you?

**Comment by mturilli** [comment]
Thanks Andre. I left a couple of comments on the PR 159

**Comment by mturilli** [comment]
Fixed in utils instead of documenting the error

**Pull request closed without merging**
